// Code generated by additional-properties DO NOT EDIT.

package health

import (
	"encoding/json"
	"strings"
)

// MarshalJSON encodes the ComponentDetail struct to JSON with additional-properties
func (c ComponentDetail) MarshalJSON() ([]byte, error) {
	type Alias ComponentDetail
	aux := (Alias)(c)
	if aux.AdditionalProperties == nil {
		aux.AdditionalProperties = map[string]interface{}{}
	}
	aux.AdditionalProperties["componentId"] = aux.ComponentId
	aux.AdditionalProperties["componentType"] = aux.ComponentType
	aux.AdditionalProperties["observedValue"] = aux.ObservedValue
	aux.AdditionalProperties["observedUnit"] = aux.ObservedUnit
	aux.AdditionalProperties["status"] = aux.Status
	aux.AdditionalProperties["affectedEndpoints"] = aux.AffectedEndpoints
	aux.AdditionalProperties["time"] = aux.Time
	aux.AdditionalProperties["output"] = aux.Output
	aux.AdditionalProperties["links"] = aux.Links
	return json.Marshal(aux.AdditionalProperties)
}

// UnmarshalJSON decodes JSON into the ComponentDetail struct with additional-properties
func (c *ComponentDetail) UnmarshalJSON(data []byte) error {
	type Alias ComponentDetail
	aux := (*Alias)(c)
	err := json.Unmarshal(data, &aux)
	if err != nil {
		return err
	}
	_ = json.Unmarshal(data, &c.AdditionalProperties)
	names := map[string]bool{
		"componentId": true, "componentid": true,
		"componentType": true, "componenttype": true,
		"observedValue": true, "observedvalue": true,
		"observedUnit": true, "observedunit": true,
		"status": true,
		"affectedEndpoints": true, "affectedendpoints": true,
		"time": true,
		"output": true,
		"links": true,
	}
	for k := range c.AdditionalProperties {
		if names[k] {
			delete(c.AdditionalProperties, k)
			continue
		}
		if names[strings.ToLower(k)] {
			delete(c.AdditionalProperties, k)
		}
	}
	if len(c.AdditionalProperties) == 0 {
		c.AdditionalProperties = nil
	}
	return nil
}
